In [1]:
import numpy as np

In [2]:
def Gauss_prob(a, b):
    X = np.zeros(len(a))
    U = a.copy()
    L = np.identity(len(a))
    B = b.copy()
    L_In = L.copy()


    for i in range(len(U)):
        if U[i,i] != 0:
            for j in range(i+1, len(U)):
                L[j,i] = U[j,i]/U[i,i]
                U[j] = U[j] - U[j,i]*U[i]/U[i,i]

    for i in range(len(U)-1, -1, -1):
        for j in range(i-1, -1, -1):
            L_In[i,j] = -L_In[i]@L[:,j]

    B = L_In@b

    for i in range(len(U)-1, -1, -1):
        s = 0
        for j in range(i, len(U)):
            s = s + X[j]*U[i,j]
        X[i] = (B[i] - s)/U[i,i] 
    
    return(L,U,B,X)

Напишем функцию для решение матрицы методом Гаусса

In [3]:
N = 4

def F(n):
    a = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            a[i, j] = 1/(i + j + 1)
    return(a)

# def messure(A):

# def F(n):
#     a = np.zeros((n, n))
#     for i in range(n):
#         for j in range(n):
#             if i == j: a[i, j] = 0
#             elif i == j + 1 or i == j - 1: a[i, j] = 1
#             else: a[i, j] = 0 
#     return(a)

b = np.ones(N)

# for i in range(N):
#     b[i] = 1/(i + 1)

print(b)

# F(N)

[1. 1. 1. 1.]


In [5]:
def Gauss_LU(a):
    U = a.copy()
    L = np.identity(len(a))

    for i in range(len(U)):
        if U[i,i] != 0:
            for j in range(i+1, len(U)):
                L[j,i] = U[j,i]/U[i,i]
                U[j] = U[j] - U[j,i]*U[i]/U[i,i]
    
    return(L,U)

def Gauss_B(L, b):
    B = np.zeros(N)
    print("b = ", b)

    for i in range(len(B)):
        s = 0
        for j in range(i+1):
            s = s + B[j]*L[i,j]
        B[i] = (b[i] - s)/L[i,i] 
    
    return(B)

L, U = Gauss_LU(F(N))

def Gauss(L, U, b):
    X = np.zeros(len(b))

    B = Gauss_B(L, b)

    for i in range(len(U)-1, -1, -1):
        s = 0
        for j in range(i, len(U)):
            s = s + X[j]*U[i,j]
        X[i] = (B[i] - s)/U[i,i] 
    
    print ("B = ", B)
    
    return X

In [6]:
X1 = Gauss(L, U, b)
print(L, '\n\n', U, '\n\n', X1)

X = L@U

# print(X - F(N))




b =  [1. 1. 1. 1.]
B =  [1.         0.5        0.16666667 0.05      ]
[[1.         0.         0.         0.        ]
 [0.5        1.         0.         0.        ]
 [0.33333333 1.         1.         0.        ]
 [0.25       0.9        1.5        1.        ]] 

 [[1.00000000e+00 5.00000000e-01 3.33333333e-01 2.50000000e-01]
 [0.00000000e+00 8.33333333e-02 8.33333333e-02 7.50000000e-02]
 [0.00000000e+00 0.00000000e+00 5.55555556e-03 8.33333333e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.57142857e-04]] 

 [  -4.   60. -180.  140.]


In [7]:
def gaussElim(a,b):
    n = len(b)
    # Elimination phase
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                #if not null define λ
                lam = a [i,k]/a[k,k]
                #we calculate the new row of the matrix
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                #we update vector b
                b[i] = b[i] - lam*b[k]
                # backward substitution
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    
    return b

In [8]:
X2 = gaussElim(F(N),b)

In [9]:
len(np.shape(L))

2

In [12]:
def scl(u,v):
    s = 0
    for k in range(len(u)):
        s += u[k]*v[k]
    return s

v = [[1,2,4],
     [2,1,2],
     [1,0,3]]

q = [[0,0,0],
     [0,0,0],
     [0,0,0]]

h = [[0,0,0],
     [0,0,0],
     [0,0,0]]

for k in range(len(v)):
    s = [0,0,0]
    for i in range(k):
        s += scl(v[k],q[i]) * q[i]

    for j in range(len(h)):
        h[k][j] = v[k][j] - s[j]
    
    q[k] = h[k]/np.sqrt(scl(h[k],h[k]))


for i in range(len(h)-1, -1, -1):
    


print (q)


[array([0.21821789, 0.43643578, 0.87287156]), array([ 0.97590007, -0.09759001, -0.19518001]), array([ 4.96506831e-16, -8.94427191e-01,  4.47213595e-01])]
